import type { Metadata } from 'next';
import { Inter, Newsreader } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import Providers from './_components/providers';

const inter = Inter({ subsets: ['latin'] });

const newsreader = Newsreader({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-newsreader',
  weight: ['300', '400', '500', '700'],
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={cn(
            'font-sans antialiased',
            inter.className,
            newsreader.variable
          )}
        >
          {children}
        </body>
      </html>
    </Providers>
  );
}

// 'max-h-screen font-sans antialiased grainy',
